# Generated by Django 5.1.4 on 2025-01-03 07:21

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_reaction_content_alter_chatroom_room_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='content',
        ),
        migrations.AddField(
            model_name='reaction',
            name='emoji_unicode',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_uuid',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
