# Generated by Django 5.1.4 on 2025-02-11 09:13

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatroom_room_avatar_alter_chatroom_room_uuid'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_file', to='files.file'),
        ),
        migrations.AddField(
            model_name='message',
            name='attached_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_img', to='files.file'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_uuid',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
